import = [
  "./themes/themes/Gruvbox-Dark.toml"
]
terminal = { }
hints = { }
debug = { }

[shell]
program = "/usr/bin/fish"

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
opacity = 1
blur = true

[scrolling]
history = 65_535

[font]
size = 14

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono Nerd Font"
  style = "Italic"

  [font.bold_italic]
  family = "JetBrainsMono Nerd Font"
  style = "Bold Italic"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#C0C5CE"

[selection]
save_to_clipboard = true

[cursor]
blink_interval = 500
blink_timeout = 0

  [cursor.style]
  shape = "Block"
  blinking = "Always"

  [cursor.vi_mode_style]
  shape = "Block"
  blinking = "Off"

[mouse]
hide_when_typing = true

  [[mouse.bindings]]
  mouse = "Middle"
  action = "PasteSelection"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"
mode = "~Search"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"
mode = "~Search"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"
mode = "~Alt"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"
mode = "~Alt"

[[keyboard.bindings]]
key = "Up"
mods = "Shift"
action = "ScrollLineUp"
mode = "~Alt"

[[keyboard.bindings]]
key = "Down"
mods = "Shift"
action = "ScrollLineDown"
mode = "~Alt"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"
mode = "~Alt"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"
mode = "~Alt"
